import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen">
      <Sidebar />
      <div className="w-full  bg-zinc-100">{children}</div>
    </div>
  );
}
